<Project Sdk="Microsoft.NET.Sdk"
         TreatAsLocalProperty="PublishAot;PublishTrimmed;PublishSingleFile;PublishReadyToRun;SelfContained;RuntimeIdentifier">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier/>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" ExcludeAssets="runtime"/>
    <PackageReference Include="Scriban" Version="7.2.6" PrivateAssets="all" GeneratePathProperty="true"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\*.sbncs"/>
  </ItemGroup>

  <PropertyGroup>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);IncludeAnalyzerDependencies</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="IncludeAnalyzerDependencies">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(PkgScriban)/lib/netstandard2.0/Scriban.dll" IncludeRuntimeDependency="false"/>
    </ItemGroup>
  </Target>

</Project>
